### ISSUE TITLE
Add submodules for umbrella repositories

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/gcp-ingestion#1122]
One of the goals for this repository is to be the monorepo for all our the projects that encompass ingestion. However, much of the code is spread across repositories. Some of these include:

* [mozilla-services/mozilla-pipeline-schemas](https://github.com/mozilla-services/mozilla-pipeline-schemas)
* [mozilla/mozilla-schema-generator](https://github.com/mozilla-services/mozilla-pipeline-schemas)
* [mozilla/jsonschema-transpiler](https://github.com/mozilla/jsonschema-transpiler)
* [mozilla/bigquery-etl](https://github.com/mozilla/bigquery-etl/)
* [mozilla/telemetry-airflow](https://github.com/mozilla/telemetry-airflow)

In abstract, these represent our schemas, etl, and scheduling repositories.

One problem with submodules is that they can be out of date. In this case, it would make sense to have a bot, not unlike dependabot or pyupbot, that would pull updates to submodules on a daily basis. We would then have information about the latest state of our projects in a single place.

**Comment by relud** [comment]
I would like to start by saying that I am against monorepos. Isolating concerns to separate repos is important for reducing the amount of tests that need to be run with each commit, reducing the amount of interference that occurs when merging pull requests, and limiting the difficulty of contributing for the first time.

I think it would save developer time and make the projects in this repo easier to interact with if we broke out some of the currently contained parts into separate repos.

> One problem with submodules is that they can be out of date. In this case, it would make sense to have a bot, not unlike dependabot or pyupbot, that would pull updates to submodules on a daily basis.

git submodules are annoying even without issues due to being out of date. They require learning an extra set of git commands to interact with, they are easy to mess up, and it can be difficult to reason about what impact a particular command will have because many people aren't familiar with how the the parent and child repos interact.

[mozilla-schema-generator](https://github.com/mozilla-services/mozilla-pipeline-schemas) and [jsonschema-transpiler](https://github.com/mozilla/jsonschema-transpiler) are linked using published versions, and I think that's an ideal approach to inter-project dependencies.

>     * [mozilla/bigquery-etl](https://github.com/mozilla/bigquery-etl/)
>     * [mozilla/telemetry-airflow](https://github.com/mozilla/telemetry-airflow)

I think that these are outside the scope of ingestion.

> We would then have information about the latest state of our projects in a single place.

If this is what you want to achieve, then I think it would be better to add documentation that references the other projects.

**Comment by acmiyaguchi** [comment]
> git submodules are annoying even without issues due to being out of date. They require learning an extra set of git commands to interact with, they are easy to mess up, and it can be difficult to reason about what impact a particular command will have because many people aren't familiar with how the the parent and child repos interact.

What I envisioned isn't necessarily a single place to contribute code to, but rather a single Github repository where the logical tree of subprojects related to ingestion can be browsed in a read-only fashion. I think our projects [sprawl across a fairly wide area](https://docs.telemetry.mozilla.org/concepts/pipeline/schemas.html#overview) and having a logical monorepo would be one form of documentation as code.

However, you're thoughts on submodules is a fair assessment. I've personally run into issues initializing and fetching updates for submodules. But, in the spirit of monorepos, here's one workflow for interacting with submodules: 

```bash
git submodule update --init
# assume mozilla-pipeline-schemas is a submodule at the root aliased to `ingestion-schemas`
cd ingestion-schemas
git remote add upstream git@github.com:acmiyaguchi/mozilla-pipeline-schemas.git
# do some work
git checkout -b work
git commit -a -m "fixed things"
git push -u upstream work
# PR is made in mozilla-services/mozilla-pipeline-schemas from acmiyaguchi/mozilla-pipeline-schemas
# PR is reviewed and merged
# submodule reference is updated
```

Overall, a complicated one. I think the idea that all of the repos could be browsed from a single one is interesting though.

> If this is what you want to achieve, then I think it would be better to add documentation that references the other projects.

This is probably more actionable, and updating the [glossary page](https://docs.telemetry.mozilla.org/tools/projects.html) would probably achieve this.

I'll leave this issue open until 2020-02-14 for further discussion, and move on if there isn't anything meaningful here.

**Comment by relud** [comment]
> a single Github repository where the logical tree of subprojects related to ingestion can be browsed in a read-only fashion. I think our projects [sprawl across a fairly wide area](https://docs.telemetry.mozilla.org/concepts/pipeline/schemas.html#overview) and having a logical monorepo would be one form of documentation as code.

In that case I think it would make sense to have a separate repo, and link all of our subprojects as submodules from there, rather than adding that here. That would also potentially be a good place for inter-project documentation and tests, should we find a need for that and not be able to fit it into a more specific project.
