### ISSUE TITLE
Use a standard failure output transform

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#118]
To match [the upstream patch @jklukas did for failure handling](https://github.com/apache/beam/pull/6586), I think using it should look like:

```java
FailureOutput.withSuccessTag(success).withFailureTag(tag, output).withFailureTag(...)
```

or perhaps instead of framing this around failures, frame it as side outputs, e.g.

```java
SideOutputs.withOutput(output, tag, ...).withOutput(...).getLastOutput()
```

**Comment by jklukas** [comment]
This is blocked for now as discussion stalled on the upstream patch. I'm considering some options for moving that effort forward.

**Comment by jklukas** [comment]
A failure handling interface has been accepted and merged in https://github.com/apache/beam/pull/7736 and should be available in Beam 2.12 to be released in a few weeks, so we'll eventually be unblocked on this refactor.

**Comment by jklukas** [comment]
2.12 is released, so we can pursue this now.

**Comment by scholtzan** [comment]
I'm trying to think this through. So is the idea here to change [MapElementsWithErrors](https://github.com/mozilla/gcp-ingestion/blob/a8040f945e0ff386f119dfefa6f4b71326d87a1f/ingestion-beam/src/main/java/com/mozilla/telemetry/transforms/MapElementsWithErrors.java) to instead use [MapElementsWithFailures](https://beam.apache.org/releases/javadoc/2.12.0/org/apache/beam/sdk/transforms/MapElements.MapWithFailures.html)? So that it would not be necessary anymore to create custom [FailureMessages](https://github.com/mozilla/gcp-ingestion/blob/a8040f945e0ff386f119dfefa6f4b71326d87a1f/ingestion-beam/src/main/java/com/mozilla/telemetry/transforms/FailureMessage.java) and process those?

**Comment by jklukas** [comment]
> I'm trying to think this through. So is the idea here to change [MapElementsWithErrors](https://github.com/mozilla/gcp-ingestion/blob/a8040f945e0ff386f119dfefa6f4b71326d87a1f/ingestion-beam/src/main/java/com/mozilla/telemetry/transforms/MapElementsWithErrors.java) to instead use [MapElementsWithFailures](https://beam.apache.org/releases/javadoc/2.12.0/org/apache/beam/sdk/transforms/MapElements.MapWithFailures.html)? 

Basically, yes, though there is some design thought to be put into exactly what that would look like, since currently we have our classes extend MapElementsWithErrors, but the MapWithFailures included with Beam would have to be called separately.

> So that it would not be necessary anymore to create custom [FailureMessages](https://github.com/mozilla/gcp-ingestion/blob/a8040f945e0ff386f119dfefa6f4b71326d87a1f/ingestion-beam/src/main/java/com/mozilla/telemetry/transforms/FailureMessage.java) and process those?

The `MapWithFailures` API requires that we pass in a function for processing exceptions into some type that can serialized using a Beam Coder. We will likely still need to maintain a custom FailureMessage type for this purpose.

I'm happy to talk through this more over Zoom if that would be helpful.

**Comment by scholtzan** [comment]
> I'm happy to talk through this more over Zoom if that would be helpful.

Sure, that'd be helpful. Whenever you have time.

**Comment by jklukas** [comment]
Final step here is to remove `WithErrors` and its uses.
