### ISSUE TITLE
Emit structured logs from ingestion-sink

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#1245]
[I'm looking through ingestion-sink logs](https://console.cloud.google.com/logs/viewer?project=moz-fx-data-ingesti-prod-d59c&minLogLevel=400&expandAll=false&timestamp=2020-04-14T16:45:42.989000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2020-04-14T16:45:43.240Z&interval=PT1H&resource=k8s_container%2Fcluster_name%2Fingestion-sink-prod-v1%2Fnamespace_name%2Fprod-ingestion-sink%2Fcontainer_name%2Fprod-ingestion-sink-app-1-telemetry-decoded-payload&scrollTimestamp=2020-04-14T16:45:27.109024398Z&dateRangeStart=2020-04-14T15:45:43.240Z) for the first time today and seeing that log entries with multiple lines are being emitted as separate entries per line, which makes navigating and searching logs difficult.

We should emit logs in JSON format with metadata that Stackdriver logging can parse.

cc @relud @whd

**Comment by jklukas** [comment]
I believe these are the relevant instructions for emitting logs in the format Google Cloud Logging expects: https://cloud.google.com/logging/docs/setup/java

**Comment by relud** [comment]
> I believe these are the relevant instructions for emitting logs in the format Google Cloud Logging expects: https://cloud.google.com/logging/docs/setup/java

As far as I can tell, those docs are for emitting logs directly to the Google Cloud Logging API, but the format expected is just newline delimited json.

**Comment by jklukas** [comment]
> As far as I can tell, those docs are for emitting logs directly to the Google Cloud Logging API, but the format expected is just newline delimited json.

I would expect that the library also handles naming fields according to standards. _Should_ we send logs directly to cloud logging? Or do we let it emit logs to stdout and let gke transmit logs to cloud logging? Are there documented best practices for GKE?

**Comment by relud** [comment]
> I would expect that the library also handles naming fields according to standards. 

for JUL it just configure the format as `%3$s: %5$s%6$s`, which [the JUL docs](https://docs.oracle.com/javase/7/docs/api/java/util/logging/SimpleFormatter.html#format(java.util.logging.LogRecord)) show to be just `${logger}: ${level}${message}`. My best guess is that the metadata and json formatting are all wrapped up in the `com.google.cloud.logging.LoggingHandler`, which is also the part that submits logs directly to Google Cloud Logging.

> _Should_ we send logs directly to cloud logging? Or do we let it emit logs to stdout and let gke transmit logs to cloud logging? Are there documented best practices for GKE?

I strongly prefer logging to stdout, because it works in the absence of GKE credentials, such as when locally running unit tests.
