### ISSUE TITLE
Add options to landfill to read from and/or write to gcs in avro format

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#24]

**Comment by acmiyaguchi** [comment]
I would like to take this one on. It looks like avro would be added as a new output file format,

https://github.com/mozilla/gcp-ingestion/blob/24c1cea1bdcb69f6f38a86f73a8ae28978cdfecf/ingestion-beam/src/main/java/com/mozilla/telemetry/options/OutputFileFormat.java#L32-L35

and then as a sink option.

https://github.com/mozilla/gcp-ingestion/blob/24c1cea1bdcb69f6f38a86f73a8ae28978cdfecf/ingestion-beam/src/main/java/com/mozilla/telemetry/options/SinkOptions.java#L49-L53

In order to write to avro, there should be a class to transform loaded json schemas into avro schemas. It looks like `mozilla-pipeline-schemas` are available resources in the project, but put behind a private interface for document validation.

https://github.com/mozilla/gcp-ingestion/blob/5e3b65f818b70c36eb632ceb7e350ace69a3a910/ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/ParsePayload.java#L82

The jsonschemas should then get transformed into [`org.apache.avro.Schema`](http://avro.apache.org/docs/1.7.7/api/java/org/apache/avro/Schema.html?is-external=true).
These schemas can then be provided to a method for writing generic avro records using a schema: [`public static AvroIO.Write<GenericRecord> writeGenericRecords(Schema schema)`](https://beam.apache.org/releases/javadoc/2.3.0/org/apache/beam/sdk/io/AvroIO.html#writeGenericRecords-org.apache.avro.Schema-).

In addition to the above, there might need to be another option to provide a schema at run-time when used in conjunction with `--outputFileFormat=avro`. This might manifest as a `--outputFileSchema`.

I would also need to figure out how to add testing resources for testing all of the functionality. The primary test of functionality should be the map-type. These are two schemas of a histogram-like payload that could be used in a unit-test.

```json
{
  "type": "object",
  "properties": {
    "document_id": {
      "type": "string"
    },
    "histograms": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "values": {
            "type": "object",
            "patternProperties": {
              "^[0-0]+$": {
                "type": "integer"
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

```json
{
  "type": "record",
  "namespace": "telemetry",
  "name": "test.1",
  "fields": [
    {
      "name": "document_id",
      "type": "string"
    },
    {
      "name": "histograms",
      "type": "map",
      "values": {
        "type": "record",
        "name": "histogram",
        "fields": [
          {
            "name": "values",
            "type": "map",
            "values": "int"
          }
        ]
      }
    }
  ]
}
```

---

I've done a little bit of searching for open-source libraries for generating avro from jsonschema. [fge/json-schema-avro](https://github.com/fge/json-schema-avro) is one option, but I'm not entirely sure about the quality of the output schemas by reading through some of the tests for map-types.

I put together a set of tests in a small development repo for json to bigquery schema in [acmiyaguchi/telemetry-schema-transpiler](https://github.com/acmiyaguchi/telemetry-schema-transpiler/tree/dev/tests). I think this is a decent set of unit-tests for documents in our pipeline. They would need to be mostly re-written for use with avro.

**Comment by jklukas** [comment]
@acmiyaguchi and I chatted yesterday, and it looks like we'll likely need to use `AvroIO` directly and its dynamic destinations feature rather than `FileIO`. So likely there's some refactoring that would need to be done, since currently the interface assumes we're just setting different options on FileIO

**Comment by acmiyaguchi** [comment]
I've done some initial groundwork to create BigQuery and Avro schemas from existing JSON Schemas. The binary in [this repo](https://github.com/acmiyaguchi/jsonschema-transpiler) generates schemas that work with maps in the core.10 ping.

I've put together a small proof of concept using the Python bindings to Beam (https://github.com/acmiyaguchi/telemetry-core-ingest-avro) which I use to generate an Avro file from a newline-delimited JSON file.
