### ISSUE TITLE
file output should allow substrings in dynamic path parts

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#267]
use case: use date portion of `submission_timestamp` attribute in landfill output path

example: `--output=gs://my-bucket/landfill/${submission_timestamp[0,10]:__NONE__}/${submission_timestamp[11,13]:__NONE__}/` yields files like `gs://my-bucket/landfill/2018-12-31/23/*`

**Comment by relud** [comment]
I made this a bug, because we can't effectively use landfill without it

**Comment by jklukas** [comment]
Time window already appears in the filename, based on our call to `.withNaming(... Write.defaultNaming(...`. I think what we'll want to do here is to implement a custom `FileNaming` subclass that uses slashes at the appropriate points. Or maybe we add an additional option for defining file naming if we think this is going to be something we want to configure differently in different jobs. As part of this, I think we should also add a `WithTimestamps` transform instance to pull out the `submission_timestamp` header if present and set the timestamp Beam.

Or, a different tack would be to have a transform that reads the `submission_timestamp` attribute and adds new `submission_date` and `submission_hour` attributes, so that we can specify `--output=gs://my-bucket/landfill/${submission_date:-__NONE__}/${submission_hour:-__NONE__}/`

**Comment by relud** [comment]
> Time window already appears in the filename

I would rather use `submission_timestamp` directly. the window isn't as useful because you get data outside the requested range because windows starting in a particular hour or day may bleed into the the next value by the window length, which should be configurable. I think a `WithTimestamps` transform would have some implications that may create additional complexity and tests, like configuring late window firings.

> Or, a different tack would be to have a transform that reads the `submission_timestamp` attribute and adds new `submission_date` and `submission_hour` attributes, so that we can specify `--output=gs://my-bucket/landfill/${submission_date:-__NONE__}/${submission_hour:-__NONE__}/`

I think this would be a good solution. We would need to make sure it is only included when it's configured, and happens after the `AddMetadata` transform if it's possible to configure both.
