### ISSUE TITLE
Permissions for BigQuery batch loads

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#377]
I just deployed the BigQuery sink with file_loads method rather than streaming and I'm seeing:

```
    "message" : "Access Denied: Project moz-fx-data-shar-nonprod-efed: The user beam-stage-sink@moz-fx-data-beam-nonprod-b5f4.iam.gserviceaccount.com does not have bigquery.jobs.create permission in project moz-fx-data-shar-nonprod-efed.",
    "reason" : "accessDenied"
```

cc @whd

**Comment by whd** [comment]
Should be fixed by https://github.com/mozilla-services/cloudops-infra/commit/e9c8e773463dbcb5343bea2ed93f4145b8876fdb.

I've added jobUser (in addition to the current dataEditor), but if you think there's a better permission to grant from https://cloud.google.com/bigquery/docs/access-control I can do that instead.

**Comment by jklukas** [comment]
Redeployed the job, and it looks happy now. I'm seeing new records flowing into BigQuery on a batch basis.
