### ISSUE TITLE
BQ sink should have get permission on subscription it is reading

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#384]
I noticed the following warning many times in the logs for the BQ sink Dataflow job:

> Failed to retrieve default ack deadline for the subscription projects/moz-fx-data-beam-nonprod-b5f4/subscriptions/sink-subscription-telemetry. generic::permission_denied: Http(403) Forbidden

I am guessing this is due to needing `pubsub.subscriptions.get` and I assume we only have consume privs on the topic. The job is still making progress, though, despite the warning.

cc @whd

**Comment by whd** [comment]
Should be fixed by https://github.com/mozilla-services/cloudops-infra/commit/393d7a4c305ffc2d4763f48e9a55cbba40da7d16

Related, I assumed similar messages would show up in the landfill dataflow job since I imagine it's doing more or less the same things with pubsub. When I went to check the job it had stopped producing data on the 8th of January. There have been a bunch of code changes since then so I'm going to redeploy it and see whether it runs into any issues.

**Comment by jklukas** [comment]
Looks good. I relaunched the BigQuery sink and haven't seen any warnings in the first 10 minutes.

**Comment by whd** [comment]
For posterity, it turns out that Dataflow jobs reading from pubsub need both `pubsub.subscriber` and `pubsub.viewer` as the latter is not a superset of the former. That both are required is probably documented somewhere, but as I was searching I came across [this](https://cloud.google.com/dataflow/docs/concepts/security-and-permissions#accessing_cloud_pubsub_topics_and_subscriptions_across_google_cloud_platform_projects) indicating cross-project access is a beta feature anyway. https://github.com/mozilla-services/cloudops-infra/commit/c76884a63ffdf85d2596d526d627b30eee9248a5 is the corresponding fix.

I determined this while re-running landfill, which is working fine now. Its permissions were probably accidentally revoked due to a terraform error that has since been resolved.

**Comment by jklukas** [comment]
It looks like the BQ sink is experiencing this problem again today after redeploying.

**Comment by jklukas** [comment]
Both landfill and sink appear to have reverted to having only subscriber permission, but not viewer according to https://console.cloud.google.com/iam-admin/iam?authuser=0&organizationId=442341870013&project=moz-fx-data-beam-nonprod-b5f4

**Comment by whd** [comment]
@jklukas the permissions you are seeing on that page are potentially expected, since those permissions are project-level and I switched to applying permissions on a per-topic basis i.e. `pubsub.viewer` should never have been applied at the project level. For permissions under https://console.cloud.google.com/cloudpubsub/topics/telemetry_decoded?project=moz-fx-data-shar-nonprod-efed&authuser=0&folder&organizationId=442341870013 it looks like the sink job should have the correct pubsub viewer/subscriber permissions. Since we're still seeing this error I am not entirely sure why it went away to begin with. I will continue to investigate.

**Comment by jklukas** [comment]
FWIW, I don't see any of these errors on the most recent run of the BQ sink job. I think they only manifest if the shuffler gets overloaded and starts waiting on leveldb operations, at which point it checks ack deadlines to see if it needs to extend them.

So I cannot say for certain whether the permission problem is fixed at this point or not.

**Comment by whd** [comment]
Ok, I believe I've sorted this out. Basically you need viewer permissions on the subscription as opposed to the topic. https://github.com/mozilla-services/cloudops-infra/commit/a192ed7767bf45d03ce9fd39b78a60700eaad710

I ran a compute instance using the various service accounts and issuing a `gcloud pubsub subscriptions describe` now succeeds in retrieving the ack deadline, so I think this should be resolved. As to why we thought we fixed it before, I would guess it's related to whether the shuffler was overloaded contributing to transience.
