### ISSUE TITLE
Consider GCS-based schema artifacts

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#398]
Right now, schemas are pulled in as resources during the build process by a script. Other artifacts such as the GeoIP database are stored in GCS and referenced as parameters.

We should consider treating schemas the same way we treat other artifacts. This decouples the build / template generation steps from the specific assets, which will make issuing dataflow updates via the update API not require new templates be generated for new schemas. Probably we'd want to make the schemas a zip bundle (you could even hit github directly), and make it a required parameter for the decoder job.

From discussion last week @jklukas  didn't have any objection, but I may have oversimplified things and there might be other considerations.

**Comment by jklukas** [comment]
This sounds fine. I'd recommend the following specifics:

- We'll change the build script to pull MPS from GitHub into test resources rather than src resources; that way, we'll still have schemas available for unit tests
- We'll add a pipeline option for specifying a GCS path, something like `--schemas-location=gs://...`
- If the `--schemas-location` option is specified, then we'll pull from that source

I'm assuming we don't want to pull from GH directly so that we don't introduce the scenario of a pipeline failing to deploy due to GH being down. But I think we should stage schemas in GCS in exactly the format that GH spits out for their archive endpoint.

**Comment by relud** [comment]
Worth noting here that schemas (and geoip db) may be loaded more than once at any time while a job is running, and failure to load can cause pipeline failures. putting resources in the jar ensures that they will definitely be available.

**Comment by jklukas** [comment]
> Worth noting here that schemas (and geoip db) may be loaded more than once at any time while a job is running, and failure to load can cause pipeline errors. putting resources in the jar ensures that they will definitely be available.

Indeed. I think that GCS is so fundamental to other pieces of the Dataflow jobs working, though, that it's reasonable to assume GCS resources will always be available.

@whd - Do you have a sense at this point of where/when we'd be updating the GCS files like schemas? Would we have a pipeline update script that includes fetching schemas from GitHub and sending to GCS before issuing a pipeline update?

**Comment by whd** [comment]
I agree that making GCS availability a runtime requirement is fine as it's already what we're doing for GeoIP, which IIRC doesn't support being loaded as jar resources the way schemas are.

WRT updates, there's basically going to be build triggers / polling jenkins jobs that mirror the various versioned artifacts to ops-managed GCS as they are updated. The ops infrastructure is then going to be trigger a job update when any of the artifacts has been updated. The idea is that in the majority of deploys (non-code change) the template won't have to be rebuilt, only the job parameters will need to be bumped e.g. (move to geoip-20180129, schemas 20180130). If no parameters change and the job is still running, terraform will know not to issue an update.
