### ISSUE TITLE
Validate ingested data against AWS

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/gcp-ingestion#427]
We need to validate that the data is the same as in the previous implementation of the ingestion pipeline, or in the cases where it is different, the reason is known and acceptable.

This issue is intended to organize some methods of validation in a systematic way. Please add any suggestions here as comments (or linked issues).

Given that the `core` pings are plumbed in based on #280, we could begin by comparing one day's worth of `core` pings, ignoring duplicates, to make sure that we end up with the same set of `documentId`s. This would have to account for slight differences in timestamps as assigned by the AWS edge vs. the GCP one which could cause a few docs to fall on the other side of a day boundary.

**Comment by whd** [comment]
In a similar vein: compare size and record counts of landfill for a particular day/days.

We're setting up the same real time monitoring system on both infrastructures, and comparing their output(s) / alerts. This will be ongoing (e.g. I will be expecting "New experiments observed" emails from both pipelines) but with some specific number checks and/or a history or documentation of the comparisons as well. I would expect daily summaries, the easiest measure to check, to be within 1%.

Of specific concern will be the content of the errors stream, since the errors will not necessarily map 1:1 between the pipelines. The error rates themselves should comparable, but we should also verify that differences are known and acceptable, and tweak the decoder if required.

Until we're deploying Dataflow jobs on CI (soon), the Geo IP database we're using will be known to be different, but at some point we should be able to verify that the GeoIP decoding is the same on both systems (assuming we push GeoIP updates roughly contemporaneously to both). This would be similar to the document id comparison but would include GeoIP.

We will eventually be able to perform this same comparison with all d2p datasets relatively easily, once they're plumbed in. More thought/effort will be required for non-d2p data.

**Comment by whd** [comment]
For some historical context that may or may not be useful, when we migrated from heka to hindsight, the primary measure we used for validation was taking all the major batch jobs, pointing them at the HS-generated datasets for some day, writing the output to a different bucket, and comparing sizes/record counts/document ids to the canonical jobs. Looking briefly back through some issues we uncovered / encountered then:

Already well-known / expected at the time: submission timestamp latency. Due to multiple levels of queues and cross-cloud-provider requests, we are expecting the difference to be greater than previously for this migration. It was fairly negligible in the AWS pipeline, where the backend systems were co-located, but makes direct comparisons difficult.

JSON encoding / UTF8 SNAFU (always and forever): there will likely be some differences between the JSON parser implementations around JSON edge cases unless we are using rapidjson. The behavior under malformed-but-mostly-correct UTF8 or other encodings may contribute a small difference in documents accepted by the GCP pipeline.

App-level decoding differences: see error stream monitoring above. This is where the majority of tweaks were ported over from the heka decoder to hindsight and I suspect there will be similar tweaks needed for GCP (but hopefully fewer, see also https://github.com/mozilla/gcp-ingestion/issues/350).

Sampling: I don't think this is presently relevant to the new pipeline, but in the current one we have a sample id generated from a crc32 of the client id. We had a code error in this crc32 generation that was caught when comparing output(s).

S3 metadata issues: this was fairly specific to the AWS S3 API and our python_moztelemetry code and I don't see an analogous issue arising in GCP, but the way we were determining how to decode data from s3 was based on some object metadata that wasn't always set correctly.

There were of course other issues but these are the ones I can remember offhand.

**Comment by mreid-moz** [comment]
See also #496 for a way to make comparisons more tractable around day boundaries.

**Comment by mreid-moz** [comment]
See also #498 for validation efforts on the ActivityStream data

**Comment by whd** [comment]
See also #629 and #630

**Comment by relud** [comment]
aws is now gone
