### ISSUE TITLE
Telemetry republisher not producing data to pubsub

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#524]
[Current job](https://console.cloud.google.com/dataflow/jobsDetail/locations/us-west1/jobs/2019-04-08_14_40_42-2105217293018940862?project=moz-fx-data-beam-nonprod-b5f4&organizationId=442341870013)
[Event topic showing no publish operations](https://app.google.stackdriver.com/services/cloud_pubsub/topics/moz-fx-data-shar-nonprod-efed/telemetry-decoded-doctype_event-6560670?project=moz-fx-data-ingesti-prod-579d)

The publishes were from my testing that the service account had the appropriate permissions to write to pubsub.

From the dataflow UI everything looks fine. @relud poked around and couldn't find anything obviously wrong, hence the issue for further investigation. The configuration looks to be correct. The current theory is that this is related to some kind of under the hood hot-swapping of java libraries that google may be doing.

The debug topic configuration (which uses a static pubsub destination) is working as expected.

**Comment by jklukas** [comment]
From the shuffler logs, I'm seeing errors like the following:

> Publishing to topic projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-doctype_${document_type} failed, will retry: generic::invalid_argument: Http(400) Bad Request

So we're not properly filling put the templates.

**Comment by jklukas** [comment]
The templates are being properly filled for tests where we're reading in from local files and writing out to local files.

My guess is that this has to do with runtime parameters, and potentially the handling of those parameters when Google dispatches pubsub to its own implementation. We set the destination topic names via doubly-nested ValueProviders.

**Comment by jklukas** [comment]
I deployed republisher in a sandbox project, with the output pointed at GCS rather than PubSub. The destinations were successfully resolved and messages were routed as expected.

This points to the problem being not about templates but about the behavior of Google's hot-swapped pubsub implementation, as @whd suggested.

**Comment by jklukas** [comment]
I opened a case with google and cc'd @whd and @relud on it.

**Comment by jklukas** [comment]
Response from Google support indicates this is a known issue and that NestedValueProvider is not likely to be supported for pubsub subscription or topic names in the immediate future. Bummer.

There are two basic approaches we can take here:

1. Make the destination topic patterns compile-time parameters, so that we can do the replacements at compile time rather than in NestedValueProvider.
2. Ditch topic patterns and instead introduce runtime parameters that take full topic names; something like `perChannelDestinations={"release":"/some/topic/path", "beta": "/other/topic/path"}` and `perDocTypeDestinations={"event": "/some/topic/path"}`.

If we ditch per-channel and just have a single sampled topic, then we reduce this ugliness a bit and just have to deal with it for per-doctype output.

**Comment by jklukas** [comment]
I'm realizing now (2) above still would require a NestedValueProvider to parse out the individual values. To specify output topics as runtime parameters, each individual output topic would need to be specified as a separate option.

I think this leads us to option (1). We have to make the topic pattern a compile-time option.
