### ISSUE TITLE
Review docTypes in AWS OTHER

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#630]
From https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/334#issuecomment-496239481. We'll throw these away in GCP without schemas, so a review of what's in there is appropriate.

**Comment by mreid-moz** [comment]
I made [a quick notebook](https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/129541/command/130046) to investigate this. It looks at all pings in OTHER since Jan 1 2019. Results (`type: count`):

```
pre-account: 2591146
cliqz-repack: 1461
mitm-prevalence-beta51: 349
fire-tv-events: 201
C:\...\aborted-session-ping: 9
err: 3
mahn: 1
key: "null": 1
íain: 1
```

Of these, `pre-account` and `cliqz-repack` look interesting. 

As far as I can tell we've already [handled `pre-account` pings](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/286).

I _think_ `cliqz-repack` is obsolete, @harterrt do you know anything about this ping?

`fire-tv-events` has a schema [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/dev/schemas/pocket/fire-tv-events).

**Comment by harterrt** [comment]
The `cliqz` ping is probably obsolete. @groovecoder can probably confirm.

**Comment by mreid-moz** [comment]
I ran this [again](https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/149350/command/149358) with the following results:
```
mitm-prevalence-beta51: 28
defineLazyModuleGetters: 1
cliqz-repack: 449
err: 5
C:\...\aborted-session-ping: 3
```

**Comment by whd** [comment]
We're considering this review done and that we don't care about any of these docTypes.
