### ISSUE TITLE
Support republishing by random sample

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#650]
See https://github.com/mozilla/gcp-ingestion/pull/517#discussion_r272722475 and subsequent discussion. This would be useful for republishing raw streams to stage for testing purposes, and I had forgotten that this hasn't been (re)implemented yet.

**Comment by jklukas** [comment]
The class we have for random sampling will use sample_id if available as an attribute on the message, and a random number generator otherwise. I'm inclined to keep that same logic for this new function; for the case of running on `telemetry-raw`, `sample_id` will never be available so it will always use the random number generator. Does that sound fine?

**Comment by whd** [comment]
Yes.
