### ISSUE TITLE
Consider adding normalized_channel to _stable clustering fields

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#772]
@sunahsuh suggested that normalized_channel would be a useful field to cluster by.

In AWS, we clustered by app name, update channel, app version, build id. Per @mreid-moz, build_id was never very useful and app_name will become less relevant in glean world. Core pings partitioned by normalized country.

My understanding of how this would work is that we build a script to iterate through stable ping tables. We iterate through once to issue copy jobs for each table to a temporary copy. Then we iterate through again, this time deleting the original table, recreating with the new clustering, and running a query to repopulate from the copy.

We would need to stage a change to the terraform configuration reflecting the new clustering configuration and merge that when we're done. As long as we can accomplish this in one day (or do it in batches with each batch happening during a day) and we start after Airflow jobs complete, we should be fine.

It's worth codifying all this. The problem is that this will become increasingly expensive as the volume of data in these tables grows.

**Comment by jklukas** [comment]
@sunahsuh additionally suggests we could in the future handle this with views to avoid expensive rewrites of the data. If we were able to provision new tables with the new clustering and simply start writing new days' pings to the new tables, we'd eventually have the pings age out such that we get the full benefit of the new clustering. Views could make those details invisible to users.

**Comment by whd** [comment]
> My understanding of how this would work is that we build a script to iterate through stable ping tables. We iterate through once to issue copy jobs for each table to a temporary copy. Then we iterate through again, this time deleting the original table, recreating with the new clustering, and running a query to repopulate from the copy.

This sounds like a correct and reasonable procedure, though see below. I fashioned a script with similar table listing for https://github.com/mozilla/gcp-ingestion/issues/773.

> 
> We would need to stage a change to the terraform configuration reflecting the new clustering configuration and merge that when we're done.

Likely we would want to delete the tables, run terraform to recreate them, and then run the query to repopulate from the copy. This is because terraform does not like when resources are deleted/recreated under it. There's a system for importing resources into existing state for cases like this, and we could codify the import process that way, but it is generally painful and I would like to avoid it if possible.

> 
> It's worth codifying all this. 

Agreed.

> The problem is that this will become increasingly expensive as the volume of data in these tables grows.

If we decide to do this, we should probably do it sooner rather than later (though see below), and we should think carefully about whether and if so what dataset/table-specific clustering fields we want for these tables.

> @sunahsuh additionally suggests we could in the future handle this with views to avoid expensive rewrites of the data. If we were able to provision new tables with the new clustering and simply start writing new days' pings to the new tables, we'd eventually have the pings age out such that we get the full benefit of the new clustering. Views could make those details invisible to users.

So much for stable. Quip aside, I believe we had considered the notion of versioning stable tables at some point. It's certainly possible to do and I'm not terribly concerned with the particulars of it since it's all post-live processing and doesn't involve deletion. We are certainly capable of provisioning new tables with different clustering, and avoiding expensive rewrites makes this strategy sound relatively appealing.

**Comment by jklukas** [comment]
We are doing this now so that we can take advantage of this clustering for the heka backfill project. We are using the newly released ability to change the clustering definition of a table in-place.

**Comment by jklukas** [comment]
This is done.
