### ISSUE TITLE
Remove use of JSONObject#toString from ingestion-sink

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#811]
the gcs output uses this method, and needs to be switched to jackson.

@jklukas how do you feel about using jackson's ObjectNode instead of org.json's JSONObject, and converting to JSONObject on an as-needed basis?

**Comment by jklukas** [comment]
I like this a lot. Jackson certainly seems like a more highly-used project than org.json and we're only using org.json because that's what the schema validator requires. We'll have to refactor some code, but should be reasonably straight-forward.

We can encapsulate all of our use of org.json to a single class and do some mvn setup to forbid importing org.json elsewhere.
