### ISSUE TITLE
Test ingestion-beam decode's main() method

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#93]
in prod this will be run with file and pubsub IO

**Comment by DeepP20** [comment]
Hey, this is my first time working on an open source project. This issue has the tag of a good first issue? How should I get started?

**Comment by jklukas** [comment]
@DeepP20 - Nice to meet you! The data platform team at Mozilla does most of our work in public repos like this largely because we like to be able to share knowledge. Most of these projects are fairly specific to Mozilla's internal needs, though, so we aren't necessarily thinking about crafting a great experience for outside contributors to participate. It makes total sense, though, that the "good first issue" tag would make it look like we're actively recruiting contributors (we were thinking about it from the perspective of a good first issue for someone on the team to get involved with this specific project). I didn't realize that the tag has special meaning to GitHub (https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/).

I'd love to know more about what drew you to the project and what gets you interested in contributing to open source software. Feel free to send me an email at the address in my profile (@jklukas).

**Comment by DeepP20** [comment]
Hey,


I have been wanting to contribute to open source software for a long time now and I have read on multiple blogs that Mozilla is a very good place to contribute Open Source software specifically in Java. I am a sophomore in college  and I am looking to polish my skills in Java programming. It would be great if you could help me get started on some other open source project that you may be familiar with. Thank you for reaching out to me.


Sincerely,
Deep.
________________________________

**Comment by jklukas** [comment]
This project is based on Apache Beam, which I've found to be a pretty supportive community so far and might be a good spot to look for Java contributions. Take a look at their [contribution guide](https://beam.apache.org/contribute/) which includes a JIRA link for starter tasks. If you make a pull request for one of those issues, feel free to tag me and I'd be happy to do an initial review.

**Comment by jklukas** [comment]
`DecoderMainTest` was introduced in https://github.com/mozilla/gcp-ingestion/pull/102 so closing this out. We can open an additional issue if there are more aspects of `Decoder` that we want to test.
